name: Release

on:
  push:
    tags: '**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          registry-url: https://registry.npmjs.org
      - uses: oven-sh/setup-bun@v2

      - run: echo PACKAGE=${TAG%@*} >> $GITHUB_ENV

      - run: bun i
      - run: bun lint
      - run: bun run build

      - run: npm stage publish
        working-directory: packages/${{ env.PACKAGE }}
      - run: gh release create $TAG --title $TAG --draft
        working-directory: packages/${{ env.PACKAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}