name: Release

on: { push: { tags: '**@[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write }
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: latest, registry-url: https://registry.npmjs.org }
      - uses: oven-sh/setup-bun@v2

      - name: Set env variables
        run: |
          [[ $TAG =~ ^((@.+?\/)?(.+))@(.+)$ ]]
          PACKAGE=${BASH_REMATCH[1]}
          DIR=${BASH_REMATCH[3]}
          VERSION=${BASH_REMATCH[4]}
          ZIP=${PACKAGE/@voicss\//voicss-}-v$VERSION.zip
          echo -e "DIR=$DIR\nPACKAGE=$PACKAGE\nVERSION=$VERSION\nZIP=$ZIP" >> $GITHUB_ENV

      - run: bun i
      - run: bun build:prod
      - run: bun test
      - run: bun lint
      - run: bun typecheck

      - run: |
          cp ../../LICENSE .
          zip -r $ZIP dist package.json LICENSE \
            $([[ $DIR == "voicss" ]] && cp ../../README.md . && echo README.md || true)
          rm -f LICENSE README.md
        working-directory: packages/${{ env.DIR }}
      - run: bun pm pack && npm publish *.tgz
        working-directory: packages/${{ env.DIR }}
      - run: gh release create $TAG --title $TAG --draft $ZIP
        working-directory: packages/${{ env.DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}